[build]
builder = "DOCKERFILE"
dockerfilePath = "client-web/Dockerfile"
watchPatterns = ["src/**", "client-web/**", "requirements.txt"]

[deploy]
healthcheckPath = "/healthz"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
